/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'clientes': RouteRecordInfo<'clientes', '/clientes', Record<never, never>, Record<never, never>>,
    'clientes-cuentas-corrientes': RouteRecordInfo<'clientes-cuentas-corrientes', '/clientes/cuentas-corrientes', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'empleados': RouteRecordInfo<'empleados', '/empleados', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'pagos-cheques': RouteRecordInfo<'pagos-cheques', '/pagos/cheques', Record<never, never>, Record<never, never>>,
    'pedidos': RouteRecordInfo<'pedidos', '/pedidos', Record<never, never>, Record<never, never>>,
    'perfil': RouteRecordInfo<'perfil', '/perfil', Record<never, never>, Record<never, never>>,
    'productos': RouteRecordInfo<'productos', '/productos', Record<never, never>, Record<never, never>>,
    'proveedores': RouteRecordInfo<'proveedores', '/proveedores', Record<never, never>, Record<never, never>>,
    'reportes': RouteRecordInfo<'reportes', '/reportes', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'usuarios': RouteRecordInfo<'usuarios', '/usuarios', Record<never, never>, Record<never, never>>,
    'usuarios-id': RouteRecordInfo<'usuarios-id', '/usuarios/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'usuarios-nuevo': RouteRecordInfo<'usuarios-nuevo', '/usuarios/nuevo', Record<never, never>, Record<never, never>>,
    'ventas': RouteRecordInfo<'ventas', '/ventas', Record<never, never>, Record<never, never>>,
    'ventas-nueva': RouteRecordInfo<'ventas-nueva', '/ventas/nueva', Record<never, never>, Record<never, never>>,
    'ventas-presupuesto': RouteRecordInfo<'ventas-presupuesto', '/ventas/presupuesto', Record<never, never>, Record<never, never>>,
  }
}
